name: Publish to NPM

on:
  push:
    branches:
      - main # or master, or whatever your default branch is

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version your project supports
        cache: 'npm'

    - run: npm ci

    - run: npm run build # Assuming you have a build step

    - run: npm test # Assuming you have tests to run

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
