name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/action-setup@v6

    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile

    - run: pnpm run lint

    - run: pnpm run build

    - run: pnpm run test:ci

    - name: Authenticate with NPM
      run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    - name: Publish to NPM
      run: npm publish
